name: LinCity Codecheck

on: workflow_dispatch

jobs:
  codecheck:
    name: Codecheck
    runs-on: ubuntu-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Install OpenGL
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          fi
        shell: bash
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/mk/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'
      - name: Configure build
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: '[`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`]'

      # Run the analysis
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/builds/ninja-multi-vcpkg/compile_commands.json

      # Upload the results to the CI.
      - uses: actions/upload-artifact@v3
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
